rag:
  chunk_size: 250
  chunk_overlap: 50

paths:
  data_dir: "data\\"
  bm25_index: "data\\bm25_index"
  qdrant_url: "http://localhost:6333"

vectorstore:
  backend: "qdrant"
  collection_name: "rag_collection"

models:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"

llm:
  backend: "ollama"     # "vllm"
  model: "llama3.2:1b"  # "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  temperature: 0.2
  max_tokens: 1024

backends:
  vllm:
    base_url: "http://vllm:8001/v1"
  ollama:
    base_url: "http://localhost:11434"
